### ISSUE TITLE
an error about plot_gene

### ISSUE THREAD

**Issue by SeqCrafter** [clwan/LTMGSCA#2]
https://github.com/clwan/LTMGSCA/blob/d3aa7e6bc38e17f44404749b612dc17b8971d2cc/R/LTMG_function_2.R#L427

This variable does not seem to be defined. If there is no global variable `Gene`, you will get an error.

**Comment by clwan** [comment]
Thanks for mentioning that. Yeah, it could be best to predefine a global variable "Gene".

**Comment by clwan** [comment]
That error has been solved. Thank you so much. Please try to install the new package. We also changed the name of this repertory, due to the conflict with other GitHub repertory.
