### ISSUE TITLE
parameter meanings

### ISSUE THREAD

**Issue by ywang65** [clwan/LTMGSCA#4]
Hi! Could you please add man folder or annotations about the meaning of parameters and outputs in each function (e.g. I'm a little confused about the meaning of k here in LTMG function)? Thanks!

**Comment by clwan** [comment]
k means the number of maximum peaks to fit the LTMG model. Usually we will select up to k peaks to fit our model, and choose the best peak number by using Bayesian Information Criteria. If you have further question, please kindly email me. I did not get notified by Github. Thanks
