### ISSUE TITLE
Method to Find Curve Intersection from plot_gene?

### ISSUE THREAD

**Issue by iSinedeus** [clwan/LTMGSCA#5]
![image](https://user-images.githubusercontent.com/62082838/85627177-f98afc00-b622-11ea-94f5-c9714ea45ea2.png)

Hello,

I was wondering if there is a way to graph and obtain the point of intersection of curves obtained from the plot_gene function? Basically like the ZxAE1 bound from the graph in the paper published. I appreciate any help you can offer.

Thank you

**Comment by clwan** [comment]
Hi, thanks for your interest. As for the intersection of the curves. It is the same like getting a root from an equation. Like to use the solve function in R, which will generate an almost true intersection. I will update our function for this perspective. Please kindly email me if you have further question.
